use_frameworks!

target 'SHBinarySearchForRange_Example' do
  pod 'SHBinarySearchForRange', :path => '../'
  
end

target 'SHBinarySearchForRange_Tests', :exclusive => true do
    pod 'SHBinarySearchForRange', :path => '../'
end
